/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AboutRouteImport } from './routes/about'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as ExperienceRouteImport } from './routes/experience'
import { Route as ProjectsRouteImport } from './routes/projects'
import { Route as ProjectsIndexRouteImport } from './routes/projects.index'
import { Route as ProjectsSlugRouteImport } from './routes/projects.$slug'
import { Route as ProjectsBusinessStrategyGrowthPlanningRouteImport } from './routes/projects.business-strategy-growth-planning'
import { Route as ProjectsDigitalWorkflowTransformationRouteImport } from './routes/projects.digital-workflow-transformation'
import { Route as ProjectsKajcoCreditTrustInfrastructureRouteImport } from './routes/projects.kajco-credit-trust-infrastructure'
import { Route as ProjectsKajcoRegulatoryRiskFoundationsRouteImport } from './routes/projects.kajco-regulatory-risk-foundations'
import { Route as ProjectsProjectReportingComplianceRouteImport } from './routes/projects.project-reporting-compliance'
import { Route as ProjectsWorkforceRetentionOnboardingRouteImport } from './routes/projects.workforce-retention-onboarding'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const ExperienceRoute = ExperienceRouteImport.update({
  id: '/experience',
  path: '/experience',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectsRoute = ProjectsRouteImport.update({
  id: '/projects',
  path: '/projects',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectsIndexRoute = ProjectsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ProjectsRoute,
} as any)
const ProjectsSlugRoute = ProjectsSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => ProjectsRoute,
} as any)
const ProjectsBusinessStrategyGrowthPlanningRoute =
  ProjectsBusinessStrategyGrowthPlanningRouteImport.update({
    id: '/business-strategy-growth-planning',
    path: '/business-strategy-growth-planning',
    getParentRoute: () => ProjectsRoute,
  } as any)
const ProjectsDigitalWorkflowTransformationRoute =
  ProjectsDigitalWorkflowTransformationRouteImport.update({
    id: '/digital-workflow-transformation',
    path: '/digital-workflow-transformation',
    getParentRoute: () => ProjectsRoute,
  } as any)
const ProjectsKajcoCreditTrustInfrastructureRoute =
  ProjectsKajcoCreditTrustInfrastructureRouteImport.update({
    id: '/kajco-credit-trust-infrastructure',
    path: '/kajco-credit-trust-infrastructure',
    getParentRoute: () => ProjectsRoute,
  } as any)
const ProjectsKajcoRegulatoryRiskFoundationsRoute =
  ProjectsKajcoRegulatoryRiskFoundationsRouteImport.update({
    id: '/kajco-regulatory-risk-foundations',
    path: '/kajco-regulatory-risk-foundations',
    getParentRoute: () => ProjectsRoute,
  } as any)
const ProjectsProjectReportingComplianceRoute =
  ProjectsProjectReportingComplianceRouteImport.update({
    id: '/project-reporting-compliance',
    path: '/project-reporting-compliance',
    getParentRoute: () => ProjectsRoute,
  } as any)
const ProjectsWorkforceRetentionOnboardingRoute =
  ProjectsWorkforceRetentionOnboardingRouteImport.update({
    id: '/workforce-retention-onboarding',
    path: '/workforce-retention-onboarding',
    getParentRoute: () => ProjectsRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/experience': typeof ExperienceRoute
  '/projects': typeof ProjectsRouteWithChildren
  '/projects/$slug': typeof ProjectsSlugRoute
  '/projects/business-strategy-growth-planning': typeof ProjectsBusinessStrategyGrowthPlanningRoute
  '/projects/digital-workflow-transformation': typeof ProjectsDigitalWorkflowTransformationRoute
  '/projects/kajco-credit-trust-infrastructure': typeof ProjectsKajcoCreditTrustInfrastructureRoute
  '/projects/kajco-regulatory-risk-foundations': typeof ProjectsKajcoRegulatoryRiskFoundationsRoute
  '/projects/project-reporting-compliance': typeof ProjectsProjectReportingComplianceRoute
  '/projects/workforce-retention-onboarding': typeof ProjectsWorkforceRetentionOnboardingRoute
  '/projects/': typeof ProjectsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/experience': typeof ExperienceRoute
  '/projects/$slug': typeof ProjectsSlugRoute
  '/projects/business-strategy-growth-planning': typeof ProjectsBusinessStrategyGrowthPlanningRoute
  '/projects/digital-workflow-transformation': typeof ProjectsDigitalWorkflowTransformationRoute
  '/projects/kajco-credit-trust-infrastructure': typeof ProjectsKajcoCreditTrustInfrastructureRoute
  '/projects/kajco-regulatory-risk-foundations': typeof ProjectsKajcoRegulatoryRiskFoundationsRoute
  '/projects/project-reporting-compliance': typeof ProjectsProjectReportingComplianceRoute
  '/projects/workforce-retention-onboarding': typeof ProjectsWorkforceRetentionOnboardingRoute
  '/projects': typeof ProjectsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/experience': typeof ExperienceRoute
  '/projects': typeof ProjectsRouteWithChildren
  '/projects/$slug': typeof ProjectsSlugRoute
  '/projects/business-strategy-growth-planning': typeof ProjectsBusinessStrategyGrowthPlanningRoute
  '/projects/digital-workflow-transformation': typeof ProjectsDigitalWorkflowTransformationRoute
  '/projects/kajco-credit-trust-infrastructure': typeof ProjectsKajcoCreditTrustInfrastructureRoute
  '/projects/kajco-regulatory-risk-foundations': typeof ProjectsKajcoRegulatoryRiskFoundationsRoute
  '/projects/project-reporting-compliance': typeof ProjectsProjectReportingComplianceRoute
  '/projects/workforce-retention-onboarding': typeof ProjectsWorkforceRetentionOnboardingRoute
  '/projects/': typeof ProjectsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/contact'
    | '/experience'
    | '/projects'
    | '/projects/$slug'
    | '/projects/business-strategy-growth-planning'
    | '/projects/digital-workflow-transformation'
    | '/projects/kajco-credit-trust-infrastructure'
    | '/projects/kajco-regulatory-risk-foundations'
    | '/projects/project-reporting-compliance'
    | '/projects/workforce-retention-onboarding'
    | '/projects/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/contact'
    | '/experience'
    | '/projects/$slug'
    | '/projects/business-strategy-growth-planning'
    | '/projects/digital-workflow-transformation'
    | '/projects/kajco-credit-trust-infrastructure'
    | '/projects/kajco-regulatory-risk-foundations'
    | '/projects/project-reporting-compliance'
    | '/projects/workforce-retention-onboarding'
    | '/projects'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/contact'
    | '/experience'
    | '/projects'
    | '/projects/$slug'
    | '/projects/business-strategy-growth-planning'
    | '/projects/digital-workflow-transformation'
    | '/projects/kajco-credit-trust-infrastructure'
    | '/projects/kajco-regulatory-risk-foundations'
    | '/projects/project-reporting-compliance'
    | '/projects/workforce-retention-onboarding'
    | '/projects/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  ContactRoute: typeof ContactRoute
  ExperienceRoute: typeof ExperienceRoute
  ProjectsRoute: typeof ProjectsRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/experience': {
      id: '/experience'
      path: '/experience'
      fullPath: '/experience'
      preLoaderRoute: typeof ExperienceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projects': {
      id: '/projects'
      path: '/projects'
      fullPath: '/projects'
      preLoaderRoute: typeof ProjectsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projects/': {
      id: '/projects/'
      path: '/'
      fullPath: '/projects/'
      preLoaderRoute: typeof ProjectsIndexRouteImport
      parentRoute: typeof ProjectsRoute
    }
    '/projects/$slug': {
      id: '/projects/$slug'
      path: '/$slug'
      fullPath: '/projects/$slug'
      preLoaderRoute: typeof ProjectsSlugRouteImport
      parentRoute: typeof ProjectsRoute
    }
    '/projects/business-strategy-growth-planning': {
      id: '/projects/business-strategy-growth-planning'
      path: '/business-strategy-growth-planning'
      fullPath: '/projects/business-strategy-growth-planning'
      preLoaderRoute: typeof ProjectsBusinessStrategyGrowthPlanningRouteImport
      parentRoute: typeof ProjectsRoute
    }
    '/projects/digital-workflow-transformation': {
      id: '/projects/digital-workflow-transformation'
      path: '/digital-workflow-transformation'
      fullPath: '/projects/digital-workflow-transformation'
      preLoaderRoute: typeof ProjectsDigitalWorkflowTransformationRouteImport
      parentRoute: typeof ProjectsRoute
    }
    '/projects/kajco-credit-trust-infrastructure': {
      id: '/projects/kajco-credit-trust-infrastructure'
      path: '/kajco-credit-trust-infrastructure'
      fullPath: '/projects/kajco-credit-trust-infrastructure'
      preLoaderRoute: typeof ProjectsKajcoCreditTrustInfrastructureRouteImport
      parentRoute: typeof ProjectsRoute
    }
    '/projects/kajco-regulatory-risk-foundations': {
      id: '/projects/kajco-regulatory-risk-foundations'
      path: '/kajco-regulatory-risk-foundations'
      fullPath: '/projects/kajco-regulatory-risk-foundations'
      preLoaderRoute: typeof ProjectsKajcoRegulatoryRiskFoundationsRouteImport
      parentRoute: typeof ProjectsRoute
    }
    '/projects/project-reporting-compliance': {
      id: '/projects/project-reporting-compliance'
      path: '/project-reporting-compliance'
      fullPath: '/projects/project-reporting-compliance'
      preLoaderRoute: typeof ProjectsProjectReportingComplianceRouteImport
      parentRoute: typeof ProjectsRoute
    }
    '/projects/workforce-retention-onboarding': {
      id: '/projects/workforce-retention-onboarding'
      path: '/workforce-retention-onboarding'
      fullPath: '/projects/workforce-retention-onboarding'
      preLoaderRoute: typeof ProjectsWorkforceRetentionOnboardingRouteImport
      parentRoute: typeof ProjectsRoute
    }
  }
}

interface ProjectsRouteChildren {
  ProjectsSlugRoute: typeof ProjectsSlugRoute
  ProjectsBusinessStrategyGrowthPlanningRoute: typeof ProjectsBusinessStrategyGrowthPlanningRoute
  ProjectsDigitalWorkflowTransformationRoute: typeof ProjectsDigitalWorkflowTransformationRoute
  ProjectsKajcoCreditTrustInfrastructureRoute: typeof ProjectsKajcoCreditTrustInfrastructureRoute
  ProjectsKajcoRegulatoryRiskFoundationsRoute: typeof ProjectsKajcoRegulatoryRiskFoundationsRoute
  ProjectsProjectReportingComplianceRoute: typeof ProjectsProjectReportingComplianceRoute
  ProjectsWorkforceRetentionOnboardingRoute: typeof ProjectsWorkforceRetentionOnboardingRoute
  ProjectsIndexRoute: typeof ProjectsIndexRoute
}

const ProjectsRouteChildren: ProjectsRouteChildren = {
  ProjectsSlugRoute: ProjectsSlugRoute,
  ProjectsBusinessStrategyGrowthPlanningRoute:
    ProjectsBusinessStrategyGrowthPlanningRoute,
  ProjectsDigitalWorkflowTransformationRoute:
    ProjectsDigitalWorkflowTransformationRoute,
  ProjectsKajcoCreditTrustInfrastructureRoute:
    ProjectsKajcoCreditTrustInfrastructureRoute,
  ProjectsKajcoRegulatoryRiskFoundationsRoute:
    ProjectsKajcoRegulatoryRiskFoundationsRoute,
  ProjectsProjectReportingComplianceRoute:
    ProjectsProjectReportingComplianceRoute,
  ProjectsWorkforceRetentionOnboardingRoute:
    ProjectsWorkforceRetentionOnboardingRoute,
  ProjectsIndexRoute: ProjectsIndexRoute,
}

const ProjectsRouteWithChildren = ProjectsRoute._addFileChildren(
  ProjectsRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  ContactRoute: ContactRoute,
  ExperienceRoute: ExperienceRoute,
  ProjectsRoute: ProjectsRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
